enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"


patches-version = "v4.8.0-dev.2"
integrations-version = "v1.9.0-dev.1"

[YouTube-Extended]
app-name = "YouTube"
rv-brand = "ReVanced Extended"
build-mode = "module"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
excluded-patches = "'Custom branding icon YouTube' 'Custom branding name YouTube' 'Custom branding heading' 'Custom package name'"

[YouTube-Music-Extended]
app-name = "YouTube Music"
rv-brand = "ReVanced Extended"
build-mode = "module"
arch = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
excluded-patches = "'Custom branding icon YouTube Music' 'Custom branding name YouTube Music' 'Custom package name'"
