enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
patches-version = "v2.224.0-dev.2"
integrations-version = "v0.151.0-dev.2"
# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube-Extended]
app-name = "YouTube"
rv-brand = "ReVanced Extended"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
cli-source = "j-hc/revanced-cli"
build-mode = "module"
version = "19.11.38"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
excluded-patches = "'Custom branding icon YouTube' 'Custom branding heading' 'Custom package name' 'Spoof player parameters' 'Hide fullscreen button'"
included-patches = "'MaterialYou'"
